extend = "./ruff.toml"

[lint]
ignore = [
    "N802", # test function naming convetions differ from source code
    "D100", # no module docstrings needed for tests
    "D101", # no class docstrings needed for tests
    "D102", # no method docstrings needed for tests
    "D103", # no function docstrings needed for tests
    "D104", # no package docstrings needed for tests
    "S101", # assert is definitely needed in test cases
    "FBT001", # booleans are often used in parametrized test cases as positional arguments, and test function argument specifications cannot usually easily include keyword arguments anyway
    "T201", # print statements in test are useful
    "BLE001", # when testing for when exception cases should not happen you need to catch Exception
    "TRY003", # tests dont need to create a custom exception classes, generally you want to throw an AssertionError with a message anyway
    "PLR2004", # tests can use magic values
    # We will not be writing our own crypto or otherwise relying on strong randomization
    "S311"
]

[lint.flake8-pytest-style]
raises-require-match-for = ["*"]
